### ISSUE TITLE
数据库表不全

### ISSUE THREAD

**Issue by daxiang1018** [Hyhyhyhyhyhyh/Django-Data-quality-system#3]
能不能更新下数据库文件，现有的sql文件里表不全，比如check_result_xt表

**Comment by Hyhyhyhyhyhyh** [comment]
1. 已更新ddl.sql以及demo数据.sql
2. check_result_xt及其它check_result_xxxxxxxx表均由check_result_template表create as select创建，例如：
```sql
create table check_result_xt as select * from check_result_template where company='xt';
create table check_result_db as select * from check_result_template where company='db';
```

**Comment by mounirzz** [comment]
I encountered this problem when starting Mysql.
Starting MySQL.. ERROR! The server quit without updating PID file (/data/mysql/data/mysql.pid).
even if I did this action : 
在266行添加--defaults-file（不加的话会报错找不到pid文件

**Comment by Hyhyhyhyhyhyh** [comment]
Which directory did you install the mysql server?

**Comment by mounirzz** [comment]
@Hyhyhyhyhyhyh same installation what you did, I installed it in the directory /data/mysql.
what concerns datadir it is in directory /data/mysql/data2.
thank you in advance,

**Comment by Hyhyhyhyhyhyh** [comment]
@mounirzz Please check if the following two parameters are set correctly：
1. `/etc/my.cnf`     datadir = /data/mysql/data2
2. `/etc/init.d/mysqld`  datadir=/data/mysql/data2

I think checking the error log (`/data/mysql/logs/mysql.log`) is a good way to find out the problem   :)

**Comment by mounirzz** [comment]
this is solved on the mysql side. **using: rm -rf /data/mysql/data2/mysql.sock** 
but I ran into another error of _virtualenv: unreconized arguments: --no-site-packages systemsExit: 2_, the problem of the virtualenv 20 version otherwise the problem of python 2.7.5 version :(.

**Comment by Hyhyhyhyhyhyh** [comment]
@mounirzz I have never deployed the project in python2 environment. 
In actually,many codes in this project use python3 syntax 😂

**Comment by mounirzz** [comment]
You are right, I did everything correct but the start of the project indicated this error:
`
(django-2.1) [pyweb@localhost ~]$ nohup gunicorn mysite.wsgi -c /data-quality/gconfig.py &
[1] 25142
(django-2.1) [pyweb@localhost ~]$ nohup: ignoring input and appending output to ‘nohup.out’
supervisorctl -c /data/data-quality/supervisor.conf start data
Error: could not find config file /data/data-quality/supervisor.conf
`
how can i generate this file /data/data-quality/supervisor.conf ??
thanks for your help.

**Comment by Hyhyhyhyhyhyh** [comment]
@mounirzz If you execute the command `nohup gunicorn mysite.wsgi -c /data-quality/gconfig.py &` successfully,you can open the link `http://ip:9000` to open the website

**Comment by mounirzz** [comment]
Thank you verrry mush for your help, just I have a little question how I can generate IP because it doesn't work with localhost: 9000, moreover I didn't use the container. :((((

**Comment by mounirzz** [comment]
@Hyhyhyhyhyhyh Pleaseeeeeeeee I can pay you for it, if you allow can we do remote connection, i'm stuck and i'm really interested in your app.

**Comment by Hyhyhyhyhyhyh** [comment]
@mounirzz i think we can use for you GMAIL mailbox for conversation
