### ISSUE TITLE
在linux上部署遇到困难

### ISSUE THREAD

**Issue by ajiangplus** [Hyhyhyhyhyhyh/Django-Data-quality-system#6]
你好作者，首先感谢你的工作。
我是一个小白，按照你的方法我git到ubuntu上并且也安装了依赖包，但是没法像你说的那样简单地用
gunicorn mysite.wsgi -c /data/pyweb/data-quality/gconfig.py &  来启动项目，你能补充详细点的部署可启动文档吗，谢谢。

**Comment by Hyhyhyhyhyhyh** [comment]
@ajiangplus 请问是有参考`docs/部署文档.md`来部署python3、mysql、nginx环境吗
