### ISSUE TITLE
关于作者的联系方式

### ISSUE THREAD

**Issue by MaxTan** [Hyhyhyhyhyhyh/Django-Data-quality-system#7]
请问能不能留一个联系方式，想跟您合作一下。 可以给我发邮件  7633025825@qq.com
谢谢

**Comment by Hyhyhyhyhyhyh** [comment]
@MaxTan 
无法发送到<7633025825@qq.com>, 原因是:收件人邮件地址（7633025825@qq.com）不存在，邮件无法送达。.

请联系您的收件人，重新核实邮箱地址，或发送到其他收信邮箱。

**Comment by MaxTan** [comment]
不好意思，打错了。 763305825@qq.com
